// Author: Saman Hosseini

pipeline {
   agent: any

   enviroment {
      DOCKER_IMAGE = "moufaso/studentsurvey645"
      K8S_NAMESPACE = "default" //change if needed
      KUBECONFIG_CRED_ID = 'kubeconfig-id'
      DOCKER_CREDENTIALS_ID = 'docker-pass'
   }

   stages {
      stage('Clone Repository') {
         steps {
            git 'https://github.com/Moufaso/Studend-Survey-Form.git'
         }
      }

      stage('Build Application') {
         steps {
            script {
               sh 'jar cvf StudentSurvey.war Student-Survey-Form/StudentSurvey/*'
            }
         }
      }

      stage('Build Docker Image') {
         steps {
            script {
               // docker.build(DOCKER_IMAGE)
               sh "docker build -t moufaso/studentsurvey645:latest Student-Survey-Form/."
            }
         }
      }

      stage('Push Docker Image') {
         steps{
            script {
               // docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
               //    docker.image(DOCKER_IMAGE).push('0.1')
               // }
               sh "docker login -u moufaso -p $DOCKER_CREDENTIALS_ID_PSW"
               sh "docker push moufaso/studentsurvey645:latest"
            }
         }
      }

      stage('Deploy to Kubernetes') {
         steps {
            script {
               sh '''
               kubectl set image deployment/studentsurvey645 studentsurvey645=${DOCKER_IMAGE}:latest -n ${K8S_NAMESPACE}
               kubectl rollout status deployment/studentsurvey645 -n ${K8S_NAMESPACE}
               '''
               // sh "kubectl set image deployment/studentsurvey studentsurvey=moufaso/studentsurevey645:0.1 -n default"
            }
         }
      }
   }

   post {
      always {
         echo 'Cleaning up...'
      }
      success {
         echo 'Deployment successful.'
      }
      failure {
         echo 'Deployment failed!'
      }
   }
}